An error occurs because the wazuh-agent parameter does not exist
NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/wazuh/recipes/agent.rb:23:in `block in from_file'
  /var/chef/cache/cookbooks/wazuh/recipes/agent.rb:22:in `from_file'
  /var/chef/cache/cookbooks/lolipop-base/recipes/wazuh.rb:8:in `from_file'